import StoreRoundedIcon from "@mui/icons-material/StoreRounded";
import LocalConvenienceStoreRoundedIcon from "@mui/icons-material/LocalConvenienceStoreRounded";
import PersonRoundedIcon from "@mui/icons-material/PersonRounded";
import LoyaltyRoundedIcon from "@mui/icons-material/LoyaltyRounded";
import SupportAgentRoundedIcon from "@mui/icons-material/SupportAgentRounded";
import LogoutRoundedIcon from "@mui/icons-material/LogoutRounded";
import KeyboardArrowLeftRoundedIcon from "@mui/icons-material/KeyboardArrowLeftRounded";
import KeyboardArrowRightRoundedIcon from "@mui/icons-material/KeyboardArrowRightRounded";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import RefreshRoundedIcon from "@mui/icons-material/RefreshRounded";
import PublishRoundedIcon from "@mui/icons-material/PublishRounded";

export const Store = () => <StoreRoundedIcon />;
export const Stores = () => <LocalConvenienceStoreRoundedIcon />;
export const Profile = () => <PersonRoundedIcon />;
export const Favourite = () => <LoyaltyRoundedIcon />;
export const SupportAgent = () => <SupportAgentRoundedIcon />;
export const LogOut = () => <LogoutRoundedIcon />;
export const ArrowLeft = () => <KeyboardArrowLeftRoundedIcon />;
export const ArrowRight = () => <KeyboardArrowRightRoundedIcon />;
export const Delete = () => <RefreshRoundedIcon />;
export const Search = () => <SearchRoundedIcon />;
export const UpLoad = () => <PublishRoundedIcon />;
